apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crb_cd
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  kind: Role
  name: role_cd
  apiGroup: rbac.authorization.k8s.io