apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
automountServiceAccountToken: true
secrets:
  - name: secret-sa-cd
