releases:
- name: kafka-prod
  namespace: prod
  chart: oci://registry-1.docker.io/bitnamicharts/kafka
  version: 28.1.1
  set:
  - name: controller.replicaCount
    value: 2
  - name: image.tag
    value: 3.5.2-debian-12-r15
- name: kafka-dev
  namespace: dev
  chart: oci://registry-1.docker.io/bitnamicharts/kafka
  version: 28.1.1
  set:
  - name: controller.replicaCount
    value: 1
  - name: listeners.interbroker.protocol
    value: plaintext
  - name: listeners.client.protocol
    value: plaintext
  - name: tls.sslClientAuth
    value: none