---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
  labels:
    app: nginx
spec:
  initContainers:
  - name: nginx-init
    image: busybox:1.28
    command: ['sh', '-c', 'wget -O /init/index.html http://example.com/index.html']
    volumeMounts:
    - mountPath: /init
      name: nginx-volume
  containers:
  - name: nginx
    image: 310581/otus-kuber-2024-01-nginx:latest
    workingDir: /homework
    ports:
    - containerPort: 8000
    volumeMounts:
    - mountPath: /homework
      name: nginx-volume
    lifecycle:
      preStop:
        exec:
          command: ['sh', '-c', 'rm -rf /homework/index.html']
  volumes:
  - name: nginx-volume
    emptyDir:
      sizeLimit: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
